version: '3.2'

# docker config
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    container_name: app_nginx

  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - .:/var/www
    container_name: app
    depends_on:
      - db

  db:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/db:/var/lib/mysql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=whitewill
    container_name: app_db

  pma:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
